---
- name: install php
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php
    - php-fpm
    - php-mysqlnd

- name: set php-fpm nginx config
  template:
    src: www.conf.j2
    dest: "/etc/php/7.4/fpm/www.conf"
  notify:
    - restart php7.4-fpm

- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: set nginx config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/sre-{{ hostvars[inventory_hostname].inventory_hostname }}-wp.ru.conf"
  notify:
   - restart nginx

- name: create sites-enabled directory
  file:
    state: directory
    dest: /etc/nginx/sites-enabled/

- name: create nginx link
  ignore_errors: "{{ ansible_check_mode }}"
  file:
    state: link
    src: "/etc/nginx/sites-available/sre-{{ hostvars[inventory_hostname].inventory_hostname }}-wp.ru.conf"
    dest: "/etc/nginx/sites-enabled/sre-{{ hostvars[inventory_hostname].inventory_hostname }}-wp.ru.conf"
  notify:
   - restart nginx

- name: enable and start nginx
  systemd:
    daemon_reload: yes
    name: nginx
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"


- name: create webroot directory
  file:
    state: directory
    path: /srv/www/
    owner: root
    group: root
    mode: 0755

- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wp-latest.tar.gz

- name: extract wordpress
  unarchive:
    src: /tmp/wp-latest.tar.gz
    dest: /tmp
    owner: nginx
    group: nginx
    copy: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Move WordPress install files
  command: mv /tmp/wordpress /srv/www/
  ignore_errors: "{{ ansible_check_mode }}"

- name: set wordpress config
  template:
    src: wp-config.php.j2
    dest: /srv/www/wordpress/wp-config.php

- name: create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present