---
- name: create webroot directory
  file:
    state: directory
    path: /var/www/
    owner: root
    group: root
    mode: 0755

- name: remove index.html
  command: rm -rf /var/www/html/index.html
  ignore_errors: "true"

- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wp-latest.tar.gz

- name: extract wordpress
  unarchive:
    src: /tmp/wp-latest.tar.gz
    dest: /tmp
    owner: nginx
    group: nginx
    copy: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: clean html
  shell: rm -rf /var/www/html/*

- name: Move WordPress install files
  shell: mv -f /tmp/wordpress/* /var/www/
  ignore_errors: "{{ ansible_check_mode }}"

- name: set wordpress config
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php

- name: create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
