---
- name: install mysql
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - mysql-client
      - mysql-server

- name: set mysql config my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: create mysql include directory
  file:
    path: /etc/mysql/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create datadir
  file:
    path: /var/lib/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
    setype: mysqld_db_t

- name: Ensure MySQL is started and enabled on boot.
  service: "name=mysql state=started enabled=true"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "MANUAL ACTION: mysql_secure_installation"
  pause:
    prompt: "Done? Press ENTER"

- name: create wordpress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: create wordpress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
