---
- name: add group node-exporter
  group:
    name: node-exporter
    state: present
    system: true

- name: create node-exporter user
  user:
    name: node-exporter
    group: node-exporter
    system: true

- name: download archive node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: extract node_exporter into tmp
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    owner: node-exporter
    group: node-exporter
    copy: no


- name: move bin file
  command: mv /tmp/node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin
  ignore_errors: "{{ ansible_check_mode }}"

- name: change owner of bin file
  file:
    path: /usr/local/bin/node_exporter
    owner: node-exporter
    group: node-exporter

- name: create service note in systemd
  template:
    src: node-exporter.service.j2
    dest: /lib/systemd/system/node-exporter.service
  notify:
    - restart node-exporter

- name: check if node-exporter is started and enabled on boot
  systemd:
    daemon_reload: yes
    name: node-exporter
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
