---
- name: set php7 repos
  yum:
    name: "{{ packages }}"
    validate_certs: no
    disable_gpg_check: true
  vars:
    packages:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    - https://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: install php7.4
  yum:
    name: "{{ packages }}"
    enablerepo: remi-php74
  vars:
    packages:
    - php
    - php-mysqlnd
    - php-cgi
    - php-gd
    - php-cli
    - php-json
    - php-mbstring
    - php-pdo
    - php-xml
    - php-pecl-zip
  ignore_errors: "{{ ansible_check_mode }}"

#- name: set php directory ownership
#  file:
#    state: directory
#    path: /var/lib/php
#    owner: root
#    group: nginx
#    mode: 0770
#
#- name: set php-fpm nginx config
#  template:
#    src: www.conf.j2
#    dest: "/etc/php-fpm.d/www.conf"
#  notify:
#    - restart php-fpm